[package]
name = "reis-scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.39.0", features = ["serialize", "overlapped-lists"] }
serde = { version = "1.0.193", features = ["derive"] }
